### PR TITLE
Adding functions to format response data for the tables

### PR DESCRIPTION
**Pull request by dmendelowitz**
This PR adds functions to format the patient, course summary, phases, and volumes into key/value pair objects so that they can be presented in a table. This was based on the example excel sheet Anthony sent us, with each function roughly corresponding to one section of the spreadsheet. Pushing the button will print the results of inputting Patient 3 to these functions to the console. Check the results and compare them to the excel sheet and see if everything makes sense.

### CODE REVIEW

**Comment by Dtphelan1** [comment]
DP1 - it looks like Volume.Laterality Code Qualifier  is missing from the final data structure. While I can see that none of the example Volumes have this information, did we want to leave that property off the data structure completely? I also cannot recall if we talked with Michelle and Anthony about this one, so please forgive me if I'm making you repeat yourself here.

**Comment by Dtphelan1** [comment]
DP2 - It also looks like we're missing Phase.Dose Per Fraction information; same question as DP1.

**Comment by dmendelowitz** [comment]
Re: DP1, Laterality is on the excel sheet, but not in the actual bundles and also not on the [profile](http://build.fhir.org/ig/HL7/codex-radiation-therapy/branches/master/StructureDefinition-codexrt-radiotherapy-volume.html), so I wasn't totally sure what to do, but left it out for now. What do you think?

Re: DP2, dose per fraction is another thing not in the bundle and not in the profile, pretty sure it's just derived by dividing total dose by number of fractions and I wasn't sure if that should happen here or in the table, but now that I think about it it, it makes sense to just do it here. I'll add it in.

**Comment by Dtphelan1** [comment]
Re: Re: DP1 – Though it's not clear, there actually is space on the Profile for the equivalent information we're looking for; it's Volume.locationQualifier property. We should probably pull from there. 

Re: Re: DP2 – I don't think we need to derive the data, but we should be trying to pull the data from where we expect it to be. Maybe? Maybe we should just talk with Rob/Z about this?

**Comment by dmendelowitz** [comment]
Re: Re: Re: DP1, Location Qualifier Code is it's own thing though?

**Comment by Dtphelan1** [comment]
Properties we will try and fail to get: 
- Patient.Deceased
- CourseSummary.TreatmentTerminationReason

Properties that will be intentionally blank: 
- Volume.LateralityQualifierCode

Properties that will be derived: 
- Phase.DosePerFraction

**Comment by dmendelowitz** [comment]
Added all the fields as described above. I must have missed this before but patient 3 actually does have a value for deceased so you should see deceased as true for patient 3 and undefined for patient 1

**Review by Dtphelan1 — APPROVED** [review]
Great work good sir

**Pull request merged**
