### PR TITLE
Support for additional patient queries

### PR DESCRIPTION
**Pull request by julianxcarter**
Adds a modal to allow for patients to be queried by the parameters specified in the RTTD IG:
- PatientId (already implemented)
- Last name (`family:exact`)
- First name (`given:exact`)
- Birth date (`birthDate`)
- Gender (`gender`)

Existing queries can be edited by clicking on their entries in the "Patient Queries" list.

### CODE REVIEW

**Review by dmendelowitz — COMMENTED** [review]
ID, name, and birth date all work great, but I noticed a couple of weird things with gender:
- Querying for 'male' only returns Patient-XRTS-01, when Patient-XRTS-03 should also be male
- Querying for 'female' seems to never resolve, the loading animation just goes on forever

**Comment by julianxcarter** [comment]
> ID, name, and birth date all work great, but I noticed a couple of weird things with gender:
> 
> * Querying for 'male' only returns Patient-XRTS-01, when Patient-XRTS-03 should also be male
> * Querying for 'female' seems to never resolve, the loading animation just goes on forever

Both of these issues should be addressed now. The `female` gender query issue was due to one of the example women on the server having a procedure without an identifier. causing the `Course Label` part of the mapping function to spaz out when it tried to access that property. I've changed the mapping functions to set the course summer and phase labels to "Unknown" when there isn't an identifier on the resource.

**Comment by dmendelowitz** [comment]
The fixes look good! Do you think it should maybe be "N/A" instead of "Unknown" for consistency with other blank values?

**Comment by julianxcarter** [comment]
> The fixes look good! Do you think it should maybe be "N/A" instead of "Unknown" for consistency with other blank values?

That's a good idea! I made the change in commit [`35279cd`](https://github.com/mcode/rttd-summary-webapp/pull/6/commits/35279cd38fd86bb3e7bca7c26a0b12f188120c0f)

**Review by dmendelowitz — APPROVED** [review]

**Pull request merged**
