### PR TITLE
Updating body site mapping for phases and course summaries

### PR DESCRIPTION
**Pull request by dmendelowitz**
This PR updates body site mapping by pulling the value for body site from the `mcode-radiotherapy-dose-delivered-to-volume` and `codexrt-radiotherapy-dose-planned-to-volume` extensions so the values get properly mapped in the "Dose Delivered to Volume" sub-tables.

To test, run the app and see that "Dose Delivered to Volume" sub-tables with multiple entries no longer have "N/A" for some entries. For example Phase 1 on Patient-XRTS-04-22A previously had "Breast structure (body structure), N/A" and should now have "Left Breast, Left Breast Boost"

Also, I noticed that Phase tables have Body Sites in the main and sub-tables. Is it necessary to have Body Sites twice on these tables? Now that we are properly mapping multiple body sites, the Body Sites in the main table ends up smashing all the values together (again if you look at Patient-XRTS-04-22A, you'll see the Body Sites in the main table as "Left BreastLeft Breast Boost"). I wanted to check if we do really want Body Sites twice in that table before I went in and fixed this

### CODE REVIEW

**Review by julianxcarter — COMMENTED** [review]
The changes here look good to me! I am not a clinician, but it does seem possible to me that two doses _could_ be delivered in two Body Sites during a single phase. We should probably check with Zeshan or Michelle and see if that's a possibility. If it is possible for two doses in the same Phase to have different sites, then I think it makes sense to keep that row on the sub tables, and do some light processing on the main row (seperating the site values with a comma if they're different, and only including a single value if they're the same). If the two volumes will always have the same value, then I think it's best to remove the `Body Sites` row from the sub-tables all together and only include a single value in the main row.

**Comment by dmendelowitz** [comment]
Latest commit renames the the new mapping in the subtable from "Body Sites" to "Volumes" and adds back the old method of Body Site mapping as its own row called "Body Sites" outside the subtable. Let me know if this correctly represents the discussion we had at standup today @julianxcarter @Dtphelan1

**Review by julianxcarter — APPROVED** [review]
Looks good to me! This lines up with what we discussed at standup.

**Comment by Dtphelan1** [comment]
Superrrr small, but could we change `Volumes` to `Volume`across the board? Aligns the pluralization better

**Comment by Dtphelan1** [comment]
lgtm

**Pull request merged**
